<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EmailRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'  => 'required|string|max:20',
            'email' => 'required|email|',
            'phone' => 'required|numeric|min:10',
        ];
    }

    public function messages()
    {
        // TODO: Change the autogenerated stub
        return [
            'name.required'  => 'Name is required',
            'email.required' => 'Email is required',
            'email.email' => 'Email is not correct',
            'phone.required' => 'Phone is required',
        ];
    }
}
